name: Angular CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  test:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and run tests
        run: |
          npm install
          npm run test:ci
          npm run build:ci
